In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model

In [2]:
df=pd.read_csv("homeprices.csv")
df

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [3]:
reg= linear_model.LinearRegression()
reg.fit(df[['area']],df.price)  #(2d array, y axis) #(independent variables, target variable)

LinearRegression()

In [8]:
reg.predict([[5000]])

C:\Users\Lenovo\AppData\Roaming\Python\Python39\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([859554.79452055])

now we are gonna save it using joblib (we can use pickle too but joblib is better)

In [24]:
import joblib

In [25]:
joblib.dump(reg,'linear_reg_model')

['linear_reg_model']

In [26]:
new_model= joblib.load('linear_reg_model')

In [27]:
new_model.predict([[5000]])

C:\Users\Lenovo\AppData\Roaming\Python\Python39\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([859554.79452055])

In [28]:
new_model.predict([[50000]])

C:\Users\Lenovo\AppData\Roaming\Python\Python39\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([6970000.])

In [29]:
new_model.predict([[10000]])

C:\Users\Lenovo\AppData\Roaming\Python\Python39\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([1538493.15068493])